name: marketplace test
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  lint:
    # Job name is Greeting
    name: Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: . --check
