name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  issues:
    types: [labeled, unlabeled]
  

jobs:
  lint:
    # Job name is Greeting
    name: Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Label updater
        uses: ./.github/actions/label-action
