name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  lint:
    # Job name is Greeting
    name: Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Black Code Formatter
        uses: ./.github/actions/black
        with:
          args: . --line-length 120
