name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  issues:
    types: [labeled, unlabeled]
  

jobs:
  lint:
    # Job name is Greeting
    name: Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: git Actions
        uses: srt32/git-actions@v0.0.3
